version: '2'

services:
  soundz:
    build: 
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/workspace/
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - docker/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dejavu
